version: '3.7'
volumes:
  redisdata:
  mongodata:

services:
  redis:
    restart: on-failure
    image: redis:6.0.1
    volumes:
      - redisdata:/data

  bull-example:
    restart: on-failure
    build: ./
    volumes:
      - ./:/app
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - EXPRESS_PORT=3000
      - BULL_REDIS_DB=1
    ports:
      - "3000:3000"